import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { twMerge } from "tailwind-merge";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { Toaster } from "react-hot-toast";
import { MantineProvider, createTheme } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" data-theme="light">
      <body className={twMerge(inter.className)}>
        <EdgeStoreProvider>
          <MantineProvider>
            <Toaster />
            <Header>{children}</Header>
          </MantineProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
